name: Cookiecutter Tests

on: [push, pull_request]


defaults:
  run:
    shell: bash -l {0}

jobs:
  tests:
    name: Application Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Create package
        uses: ./.github/actions/create-package

      - name: Backend tests
        run: py.test
        working-directory: test-app

      - name: Frontend tests
        run: yarn test
        working-directory: test-app

      - name: Lint
        run: |
          jlpm
          jlpm run build
          jlpm run lint:check
        working-directory: test-app

  ui-tests:
    name: Visual Regression
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Create package
        uses: ./.github/actions/create-package

      - name: Install browser
        run: |
          jlpm install
          jlpm playwright install chromium
        working-directory: test-app/ui-tests

      - name: Launch
        run: jlpm start:detached > /tmp/jupyterlab_server.log 2>&1
        working-directory: test-app/ui-tests

      - name: Wait for JupyterLab
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http-get://localhost:8866/
          timeout: 360000

      - name: Widget rendering tests
        run: jlpm run test
        working-directory: test-app/ui-tests

      - name: Upload Playwright Test assets
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: lab-test-assets
          path: |
            test-app/ui-tests/test-results

      - name: Upload Playwright Test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: lab-test-report
          path: |
            test-app/ui-tests/playwright-report

      - name: Update snapshots
        if: failure()
        run: |
          # remove previous snapshots from other browser
          jlpm rimraf "tests/**/*-snapshots/*.png"
          # generate new snapshots
          jlpm run test:update
        working-directory: test-app/ui-tests

      - name: Print JupyterLab logs
        if: always()
        run: cat /tmp/jupyterlab_server.log
